'use client';
import Link from 'next/link';
import type { ThemeCustomizerField } from '@/lib/themes/manifest.schema';
type RepeatItem=Record<string,string>;
type Props={field:ThemeCustomizerField;value:string;onChange:(value:string)=>void};
export default function CustomizerField({field,value,onChange}:Props){
 if(field.type==='shortcut')return <div className="customizer-field"><label>{field.label}</label><Link className="customizer-shortcut" href={field.shortcutUrl||'#'} target="_blank">Mở trình quản lý ↗</Link></div>;
 if(field.type==='toggle')return <div className="customizer-field"><label>{field.label}</label><label className="customizer-switch"><input type="checkbox" checked={value==='true'} onChange={e=>onChange(String(e.target.checked))}/><span>{value==='true'?'Đang bật':'Đang tắt'}</span></label></div>;
 if(field.type==='select')return <div className="customizer-field"><label htmlFor={`customizer-${field.id}`}>{field.label}</label><select id={`customizer-${field.id}`} value={value} onChange={e=>onChange(e.target.value)}>{field.options?.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></div>;
 if(field.type==='color')return <div className="customizer-field"><label>{field.label}</label><div style={{display:'flex',gap:8}}><input aria-label={field.label} type="color" value={value||'#0c64d0'} onChange={e=>onChange(e.target.value)} style={{width:44}}/><input value={value} onChange={e=>onChange(e.target.value)}/></div></div>;
 if(field.type==='image')return <div className="customizer-field"><label>{field.label}</label><div className="customizer-media">{value&&<img src={value} alt="Xem trước"/>}<input value={value} placeholder="URL ảnh từ Thư viện Media" onChange={e=>onChange(e.target.value)}/><Link className="customizer-shortcut" href="/admin/media" target="_blank">Mở Thư viện Media ↗</Link></div></div>;
 if(field.type==='repeater'){let items:RepeatItem[]=[];try{items=JSON.parse(value||'[]')}catch{};const change=(next:RepeatItem[])=>onChange(JSON.stringify(next));return <div className="customizer-field"><label>{field.label}</label><div className="customizer-repeater">{items.map((item,index)=><div className="customizer-repeat-item" key={index}><div className="customizer-repeat-head"><span>Mục {index+1}</span><div className="customizer-repeat-actions"><button type="button" aria-label="Di chuyển lên" disabled={!index} onClick={()=>{const n=[...items];[n[index-1],n[index]]=[n[index],n[index-1]];change(n)}}>↑</button><button type="button" aria-label="Di chuyển xuống" disabled={index===items.length-1} onClick={()=>{const n=[...items];[n[index+1],n[index]]=[n[index],n[index+1]];change(n)}}>↓</button><button type="button" aria-label="Xóa mục" onClick={()=>change(items.filter((_,i)=>i!==index))}>×</button></div></div>{field.itemFields?.map(child=>child.type==='textarea'?<textarea key={child.id} aria-label={child.label} placeholder={child.label} value={item[child.id]||''} onChange={e=>{const n=[...items];n[index]={...item,[child.id]:e.target.value};change(n)}}/>:<input key={child.id} type={child.type==='url'?'url':'text'} aria-label={child.label} placeholder={child.label} value={item[child.id]||''} onChange={e=>{const n=[...items];n[index]={...item,[child.id]:e.target.value};change(n)}}/>)}</div>)}<button type="button" className="customizer-add" disabled={items.length>=(field.maxItems||20)} onClick={()=>change([...items,Object.fromEntries((field.itemFields||[]).map(child=>[child.id,child.default||'']))])}>+ Thêm mục</button></div></div>}
 const input=field.type==='textarea'?<textarea id={`customizer-${field.id}`} value={value} maxLength={field.maxLength} onChange={e=>onChange(e.target.value)}/>:<input id={`customizer-${field.id}`} type={field.type==='number'?'number':field.type==='url'?'url':'text'} value={value} min={field.min} max={field.max} maxLength={field.maxLength} onChange={e=>onChange(e.target.value)}/>;return <div className="customizer-field"><label htmlFor={`customizer-${field.id}`}>{field.label}</label>{input}{field.description&&<small>{field.description}</small>}</div>;
}
