import { prisma } from '@/lib/prisma';

export interface RestTaxonomyPreview { baseUrl:string; categories:number; tags:number; posts:number }
export interface RestTaxonomyResult extends RestTaxonomyPreview { dryRun:boolean; matched:number; matchedByLegacyId:number; matchedBySlug:number; unmatched:number; updated:number; logs:string[] }
type WpTerm={id:number;name:string;slug:string;description?:string;parent:number};
type WpPost={id:number;slug:string;categories:number[];tags:number[]};

function normalizeBaseUrl(input:string){const url=new URL(input.trim());if(!['http:','https:'].includes(url.protocol))throw new Error('URL WordPress phải dùng HTTP hoặc HTTPS.');if(['localhost','127.0.0.1','::1'].includes(url.hostname)||/^(10\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.)/.test(url.hostname))throw new Error('Không cho phép REST API ở mạng nội bộ.');return `${url.protocol}//${url.host}`}
async function wpFetch<T>(url:string):Promise<{data:T;pages:number}>{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);try{const response=await fetch(url,{signal:controller.signal,headers:{Accept:'application/json','User-Agent':'Ezitrans-CMS-Importer/1.0'},cache:'no-store'});if(!response.ok)throw new Error(`WordPress REST API trả HTTP ${response.status}`);return{data:await response.json() as T,pages:Math.max(1,Number(response.headers.get('x-wp-totalpages')||1))}}finally{clearTimeout(timer)}}
async function fetchCollection<T>(base:string,endpoint:string,fields:string):Promise<T[]>{const first=await wpFetch<T[]>(`${base}/wp-json/wp/v2/${endpoint}?per_page=100&page=1&_fields=${fields}`);const all=[...first.data];for(let page=2;page<=first.pages;page++){const next=await wpFetch<T[]>(`${base}/wp-json/wp/v2/${endpoint}?per_page=100&page=${page}&_fields=${fields}`);all.push(...next.data)}return all}
export async function fetchWordPressTaxonomy(baseInput:string){const baseUrl=normalizeBaseUrl(baseInput);const [categories,tags,posts]=await Promise.all([fetchCollection<WpTerm>(baseUrl,'categories','id,name,slug,description,parent'),fetchCollection<WpTerm>(baseUrl,'tags','id,name,slug,description,parent'),fetchCollection<WpPost>(baseUrl,'posts','id,slug,categories,tags')]);return{baseUrl,categories,tags,posts}}
export async function previewWordPressTaxonomy(baseInput:string):Promise<RestTaxonomyPreview>{const data=await fetchWordPressTaxonomy(baseInput);return{baseUrl:data.baseUrl,categories:data.categories.length,tags:data.tags.length,posts:data.posts.length}}
export async function syncWordPressTaxonomy(baseInput:string,dryRun=false):Promise<RestTaxonomyResult>{const source=await fetchWordPressTaxonomy(baseInput);const result:RestTaxonomyResult={baseUrl:source.baseUrl,categories:source.categories.length,tags:source.tags.length,posts:source.posts.length,dryRun,matched:0,matchedByLegacyId:0,matchedBySlug:0,unmatched:0,updated:0,logs:[]};const categoryMap=new Map<number,number>(),tagMap=new Map<number,number>();
 for(const term of source.categories){if(dryRun)continue;const row=await prisma.category.upsert({where:{slug:term.slug},update:{name:term.name,description:term.description||null},create:{name:term.name,slug:term.slug,description:term.description||null}});categoryMap.set(term.id,row.id)}
 if(!dryRun){for(const term of source.categories.filter(t=>t.parent)){const id=categoryMap.get(term.id),parentId=categoryMap.get(term.parent);if(id&&parentId)await prisma.category.update({where:{id},data:{parentId}})}for(const term of source.tags){const row=await prisma.tag.upsert({where:{slug:term.slug},update:{name:term.name},create:{name:term.name,slug:term.slug}});tagMap.set(term.id,row.id)}}
 for(const wpPost of source.posts){let post=await prisma.post.findUnique({where:{legacyId:wpPost.id},select:{id:true,slug:true}});if(post)result.matchedByLegacyId++;else{post=await prisma.post.findUnique({where:{slug:wpPost.slug},select:{id:true,slug:true}});if(post)result.matchedBySlug++}if(!post){result.unmatched++;if(result.logs.length<30)result.logs.push(`Không tìm thấy bài WP #${wpPost.id} (${wpPost.slug})`);continue}result.matched++;if(!dryRun){const categories=wpPost.categories.map(id=>categoryMap.get(id)).filter((id):id is number=>!!id).map(id=>({id}));const tags=wpPost.tags.map(id=>tagMap.get(id)).filter((id):id is number=>!!id).map(id=>({id}));await prisma.post.update({where:{id:post.id},data:{categories:{set:categories},tags:{set:tags}}});result.updated++}}
 result.logs.unshift(`${dryRun?'Dry run':'Đồng bộ'} hoàn tất: khớp ${result.matched}/${result.posts} bài, không tìm thấy ${result.unmatched}.`);return result}
