import fs from 'fs';
import { XMLParser } from 'fast-xml-parser';

export interface WxrAuthor { id: number; login: string; email: string; displayName: string }
export interface WxrComment { id: number; author: string; email: string; url: string; ip: string; date: Date; content: string; approved: string; parentId: number; userId: number }
export interface WxrTermRef { domain: string; nicename: string; name: string }
export interface WxrItem { id: number; title: string; link: string; creator: string; content: string; excerpt: string; date: Date; modified: Date; status: string; slug: string; parentId: number; postType: string; attachmentUrl: string; terms: WxrTermRef[]; meta: Record<string,string>; comments: WxrComment[] }
export interface WxrDocument { version: string; title: string; description: string; language: string; baseSiteUrl: string; baseBlogUrl: string; authors: WxrAuthor[]; categories: Array<{id:number;nicename:string;parent:string;name:string}>; tags: Array<{id:number;slug:string;name:string}>; items: WxrItem[] }
export interface WxrSummary { format:'xml'; wxrVersion:string; baseSiteUrl:string; posts:number; pages:number; users:number; categories:number; tags:number; comments:number; attachments:number; images:number; metadata:number; totalTerms:number }

const asArray=<T>(value:T|T[]|null|undefined):T[]=>value==null?[]:Array.isArray(value)?value:[value];
const text=(value:unknown):string=>{if(value==null)return '';if(Array.isArray(value))return value.map(text).join('');if(typeof value==='object'&&'#text' in (value as object))return text((value as {'#text':unknown})['#text']);return String(value)};
const integer=(value:unknown)=>Number.parseInt(text(value),10)||0;
const date=(value:unknown)=>{const raw=text(value).trim();if(!raw||raw.startsWith('0000-00-00'))return new Date();const parsed=new Date(raw.includes('T')?raw:raw.replace(' ','T')+'Z');return Number.isNaN(parsed.getTime())?new Date():parsed};
export function assertSafeWxr(xml:string){if(/<!DOCTYPE|<!ENTITY/i.test(xml))throw new Error('WXR không hợp lệ: DOCTYPE/ENTITY không được hỗ trợ.');if(!/<wp:wxr_version>\s*1\.[12]\s*<\/wp:wxr_version>/i.test(xml))throw new Error('File XML không phải WordPress WXR 1.1/1.2 hợp lệ.')}
export function parseWxrXml(xml:string):WxrDocument{
 assertSafeWxr(xml);
 const parser=new XMLParser({ignoreAttributes:false,attributeNamePrefix:'@_',textNodeName:'#text',parseTagValue:false,trimValues:false,processEntities:true,cdataPropName:'#text',isArray:(_n,p)=>['rss.channel.item','rss.channel.wp:author','rss.channel.wp:category','rss.channel.wp:tag','rss.channel.item.category','rss.channel.item.wp:postmeta','rss.channel.item.wp:comment'].includes(String(p))});
 const channel=parser.parse(xml)?.rss?.channel;if(!channel)throw new Error('Không tìm thấy channel WXR trong file XML.');
 const authors=asArray<any>(channel['wp:author']).map(a=>({id:integer(a['wp:author_id']),login:text(a['wp:author_login']).trim(),email:text(a['wp:author_email']).trim(),displayName:text(a['wp:author_display_name']).trim()}));
 const categories=asArray<any>(channel['wp:category']).map(c=>({id:integer(c['wp:term_id']),nicename:text(c['wp:category_nicename']).trim(),parent:text(c['wp:category_parent']).trim(),name:text(c['wp:cat_name']).trim()}));
 const tags=asArray<any>(channel['wp:tag']).map(t=>({id:integer(t['wp:term_id']),slug:text(t['wp:tag_slug']).trim(),name:text(t['wp:tag_name']).trim()}));
 const items=asArray<any>(channel.item).map(item=>{const meta:Record<string,string>={};for(const e of asArray<any>(item['wp:postmeta'])){const k=text(e['wp:meta_key']).trim();if(k)meta[k]=text(e['wp:meta_value'])}const comments=asArray<any>(item['wp:comment']).map(c=>({id:integer(c['wp:comment_id']),author:text(c['wp:comment_author']).trim(),email:text(c['wp:comment_author_email']).trim(),url:text(c['wp:comment_author_url']).trim(),ip:text(c['wp:comment_author_IP']).trim(),date:date(c['wp:comment_date_gmt']||c['wp:comment_date']),content:text(c['wp:comment_content']),approved:text(c['wp:comment_approved']).trim(),parentId:integer(c['wp:comment_parent']),userId:integer(c['wp:comment_user_id'])}));const terms=asArray<any>(item.category).map(t=>({domain:text(t['@_domain']).trim(),nicename:text(t['@_nicename']).trim(),name:text(t['#text']).trim()}));return{id:integer(item['wp:post_id']),title:text(item.title).trim(),link:text(item.link).trim(),creator:text(item['dc:creator']).trim(),content:text(item['content:encoded']),excerpt:text(item['excerpt:encoded']),date:date(item['wp:post_date_gmt']||item['wp:post_date']),modified:date(item['wp:post_modified_gmt']||item['wp:post_modified']),status:text(item['wp:status']).trim(),slug:text(item['wp:post_name']).trim(),parentId:integer(item['wp:post_parent']),postType:text(item['wp:post_type']).trim(),attachmentUrl:text(item['wp:attachment_url']).trim(),terms,meta,comments}});
 return{version:text(channel['wp:wxr_version']).trim(),title:text(channel.title).trim(),description:text(channel.description).trim(),language:text(channel.language).trim(),baseSiteUrl:text(channel['wp:base_site_url']).trim(),baseBlogUrl:text(channel['wp:base_blog_url']).trim(),authors,categories,tags,items};
}
export const parseWxrFile=(filePath:string)=>parseWxrXml(fs.readFileSync(filePath,'utf8'));
export function summarizeWxr(doc:WxrDocument):WxrSummary{const attachments=doc.items.filter(i=>i.postType==='attachment').length;const inline=doc.items.reduce((s,i)=>s+(i.content.match(/<img\b/gi)?.length||0),0);return{format:'xml',wxrVersion:doc.version,baseSiteUrl:doc.baseSiteUrl,posts:doc.items.filter(i=>i.postType==='post').length,pages:doc.items.filter(i=>i.postType==='page').length,users:doc.authors.length,categories:doc.categories.length,tags:doc.tags.length,comments:doc.items.reduce((s,i)=>s+i.comments.length,0),attachments,images:Math.max(attachments,inline),metadata:doc.items.reduce((s,i)=>s+Object.keys(i.meta).length,0),totalTerms:doc.categories.length+doc.tags.length}}
