import { createHash, createPublicKey, verify } from 'crypto';
import { compareSemanticVersions, isSemanticVersion, type ReleaseChannel } from '@/lib/version';
export interface CoreReleaseManifest {product:'lexi-cms';channel:ReleaseChannel;version:string;image:string;minimumVersion:string;releasedAt:string;requiresBackup:boolean;requiresMigration:boolean;rollbackCompatible:boolean;checksum?:string;changelog?:string[];changelogUrl?:string;signature?:string;}
function canonicalize(m:CoreReleaseManifest){const {signature,...payload}=m;return JSON.stringify(payload,Object.keys(payload).sort());}
export function validateManifest(m:any): asserts m is CoreReleaseManifest {if(!m||m.product!=='lexi-cms')throw new Error('Unsupported release product.');if(!['internal','canary','stable'].includes(m.channel))throw new Error('Invalid release channel.');if(!isSemanticVersion(m.version)||!isSemanticVersion(m.minimumVersion))throw new Error('Invalid release semantic version.');if(typeof m.image!=='string'||!m.image.includes('@sha256:'))throw new Error('Release image must use an immutable sha256 digest.');if(!/^https?:\/\//.test(process.env.LEXI_UPDATE_REGISTRY_URL||'https://registry.invalid')&&process.env.NODE_ENV==='production')throw new Error('Update registry must use HTTPS.');}
export function verifyManifestSignature(m:CoreReleaseManifest){const key=process.env.LEXI_UPDATE_PUBLIC_KEY;if(!key)return process.env.NODE_ENV!=='production';if(!m.signature)return false;return verify(null,Buffer.from(canonicalize(m)),createPublicKey(key.replace(/\\n/g,'\n')),Buffer.from(m.signature,'base64'));}
export function releaseCompatibility(m:CoreReleaseManifest,current:string){return {updateAvailable:compareSemanticVersions(m.version,current)>0,currentSupported:compareSemanticVersions(current,m.minimumVersion)>=0};}
export async function fetchLatestRelease(channel:ReleaseChannel):Promise<CoreReleaseManifest|null>{const base=process.env.LEXI_UPDATE_REGISTRY_URL;if(!base)return null;const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),8000);try{const response=await fetch(`${base.replace(/\/$/,'')}/v1/releases/${channel}/latest`,{cache:'no-store',signal:controller.signal,headers:{Accept:'application/json'}});if(!response.ok)throw new Error(`Registry returned HTTP ${response.status}.`);const manifest=await response.json();validateManifest(manifest);if(!verifyManifestSignature(manifest))throw new Error('Release manifest signature is invalid.');return manifest;}finally{clearTimeout(timeout);}}
export function manifestFingerprint(m:CoreReleaseManifest){return createHash('sha256').update(canonicalize(m)).digest('hex');}
