'use client';

import { useEffect, useMemo, useState } from 'react';
import { ChevronDown, ChevronUp, Eye, EyeOff, Laptop, MessageCircle, MonitorSmartphone, Plus, Save, Smartphone, Trash2 } from 'lucide-react';
import { createChannel, DEFAULT_CONTACT_WIDGET_CONFIG } from '../lib/contactWidgetConfig';
import type { ContactChannel, ContactChannelType, ContactWidgetConfig } from '../lib/contactWidgetTypes';

const channelOptions: Array<{ type: ContactChannelType; label: string }> = [
  { type:'hotline', label:'Hotline' },{ type:'zalo', label:'Zalo' },{ type:'messenger', label:'Messenger' },{ type:'whatsapp', label:'WhatsApp' },{ type:'telegram', label:'Telegram' },{ type:'viber', label:'Viber' },{ type:'facebook', label:'Facebook' },{ type:'instagram', label:'Instagram' },{ type:'tiktok', label:'TikTok' },{ type:'youtube', label:'YouTube' },{ type:'map', label:'Google Maps' },{ type:'email', label:'Email' },{ type:'custom', label:'Liên kết khác' },
];
const typeLabel = (type: ContactChannelType) => channelOptions.find(option => option.type === type)?.label || type;

export function ContactSettingsPage() {
  const [config, setConfig] = useState<ContactWidgetConfig>(DEFAULT_CONTACT_WIDGET_CONFIG);
  const [selectedId, setSelectedId] = useState('');
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [notice, setNotice] = useState<{ type:'success'|'error'; text:string }|null>(null);
  const [previewMobile, setPreviewMobile] = useState(true);
  const [addType, setAddType] = useState<ContactChannelType>('hotline');
  const selected = useMemo(() => config.channels.find(channel => channel.id === selectedId), [config.channels, selectedId]);

  useEffect(() => { fetch('/api/plugins/contact-widget/settings').then(response => response.json()).then(data => { if(data.success){setConfig(data.config);setSelectedId(data.config.channels[0]?.id||'');} else setNotice({type:'error',text:data.error}); }).catch(()=>setNotice({type:'error',text:'Không tải được cấu hình.'})).finally(()=>setLoading(false)); }, []);
  const patch = (changes: Partial<ContactWidgetConfig>) => setConfig(current => ({ ...current, ...changes }));
  const patchChannel = (id: string, changes: Partial<ContactChannel>) => setConfig(current => ({ ...current, channels: current.channels.map(channel => channel.id === id ? { ...channel, ...changes } : channel) }));
  const addChannel = () => { const channel=createChannel(addType,'',config.channels.length); setConfig(current=>({...current,channels:[...current.channels,channel]}));setSelectedId(channel.id); };
  const removeChannel = (id:string) => setConfig(current=>{const channels=current.channels.filter(channel=>channel.id!==id);setSelectedId(channels[0]?.id||'');return {...current,channels,mobileBarChannelIds:current.mobileBarChannelIds.filter(item=>item!==id)};});
  const move = (id:string,direction:-1|1) => setConfig(current=>{const channels=[...current.channels];const index=channels.findIndex(channel=>channel.id===id);const target=index+direction;if(index<0||target<0||target>=channels.length)return current;[channels[index],channels[target]]=[channels[target],channels[index]];return {...current,channels};});
  const save = async () => { setSaving(true);setNotice(null);try{const response=await fetch('/api/plugins/contact-widget/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(config)});const data=await response.json();if(!response.ok||!data.success)throw new Error(data.error||'Không thể lưu');setConfig(data.config);setNotice({type:'success',text:'Đã lưu Contact Hub thành công.'});}catch(error){setNotice({type:'error',text:error instanceof Error?error.message:'Không thể lưu'});}finally{setSaving(false);} };
  if(loading)return <div className="min-h-[420px] grid place-items-center text-sm text-slate-500">Đang tải Contact Hub...</div>;

  return <div className="max-w-[1380px] mx-auto pb-20">
    <header className="flex flex-col lg:flex-row lg:items-center justify-between gap-4 mb-6 border-b border-slate-200 pb-5"><div><div className="flex items-center gap-2"><span className="w-10 h-10 rounded-xl bg-brand-600 text-white grid place-items-center"><MessageCircle size={20}/></span><div><h1 className="text-2xl font-bold text-slate-900">Contact Hub</h1><p className="text-xs text-slate-500 mt-1">Quản lý các kênh liên hệ và xem trước chính xác trước khi xuất bản.</p></div></div></div><div className="flex items-center gap-3"><label className="flex items-center gap-2 text-xs font-bold text-slate-600"><input type="checkbox" checked={config.enabled} onChange={event=>patch({enabled:event.target.checked})}/> Bật widget</label><button onClick={save} disabled={saving} className="min-h-10 px-5 rounded-xl bg-brand-600 text-white text-xs font-bold inline-flex items-center gap-2 disabled:opacity-60"><Save size={15}/>{saving?'Đang lưu...':'Lưu thay đổi'}</button></div></header>
    {notice&&<div className={`mb-5 rounded-xl border p-3 text-xs font-bold ${notice.type==='success'?'bg-emerald-50 border-emerald-200 text-emerald-700':'bg-rose-50 border-rose-200 text-rose-700'}`}>{notice.text}</div>}
    <div className="grid xl:grid-cols-[270px_minmax(0,1fr)_360px] gap-5 items-start">
      <aside className="bg-white border border-slate-200 rounded-2xl p-4 shadow-sm"><div className="flex items-center justify-between mb-3"><h2 className="text-sm font-bold text-slate-800">Kênh liên hệ</h2><span className="text-[10px] bg-slate-100 px-2 py-1 rounded-full">{config.channels.length}/20</span></div><div className="grid gap-2 max-h-[520px] overflow-auto">{config.channels.map((channel)=><button key={channel.id} onClick={()=>setSelectedId(channel.id)} className={`w-full text-left p-3 rounded-xl border flex items-center gap-2 ${selectedId===channel.id?'border-brand-500 bg-brand-50':'border-slate-200 hover:bg-slate-50'}`}><span className="w-3 h-3 rounded-full" style={{background:channel.color}}/><span className="flex-1 min-w-0"><strong className="text-xs block truncate">{channel.label||typeLabel(channel.type)}</strong><small className="text-[10px] text-slate-400">{typeLabel(channel.type)}</small></span>{channel.enabled?<Eye size={14}/>:<EyeOff size={14} className="text-slate-400"/>}<span className="grid gap-0.5"><span onClick={event=>{event.stopPropagation();move(channel.id,-1)}}><ChevronUp size={13}/></span><span onClick={event=>{event.stopPropagation();move(channel.id,1)}}><ChevronDown size={13}/></span></span></button>)}</div><div className="mt-4 flex gap-2"><select value={addType} onChange={event=>setAddType(event.target.value as ContactChannelType)} className="min-w-0 flex-1 border border-slate-200 rounded-lg px-2 text-xs">{channelOptions.map(option=><option key={option.type} value={option.type}>{option.label}</option>)}</select><button onClick={addChannel} className="w-10 h-10 grid place-items-center rounded-lg bg-slate-900 text-white" aria-label="Thêm kênh"><Plus size={17}/></button></div></aside>
      <main className="bg-white border border-slate-200 rounded-2xl p-5 sm:p-7 shadow-sm">
        {selected?<div className="space-y-6"><div className="flex justify-between items-center"><div><span className="text-[10px] uppercase tracking-widest text-brand-600 font-black">{typeLabel(selected.type)}</span><h2 className="font-bold text-slate-900 mt-1">Chỉnh sửa kênh</h2></div><button onClick={()=>removeChannel(selected.id)} className="w-9 h-9 grid place-items-center rounded-lg text-rose-600 bg-rose-50" aria-label="Xóa kênh"><Trash2 size={16}/></button></div><div className="grid sm:grid-cols-2 gap-5"><label className="grid gap-2 text-xs font-bold text-slate-700">Nhãn hiển thị<input value={selected.label} onChange={event=>patchChannel(selected.id,{label:event.target.value})} className="h-11 border border-slate-200 rounded-xl px-3 font-normal"/></label><label className="grid gap-2 text-xs font-bold text-slate-700">Màu thương hiệu<div className="h-11 border border-slate-200 rounded-xl px-3 flex items-center gap-3"><input type="color" value={selected.color} onChange={event=>patchChannel(selected.id,{color:event.target.value})}/><span>{selected.color}</span></div></label><label className="grid gap-2 text-xs font-bold text-slate-700 sm:col-span-2">Số điện thoại / Username / URL<input value={selected.value} onChange={event=>patchChannel(selected.id,{value:event.target.value})} placeholder="Nhập thông tin liên hệ" className="h-11 border border-slate-200 rounded-xl px-3 font-normal"/></label><label className="grid gap-2 text-xs font-bold text-slate-700 sm:col-span-2">Tin nhắn điền sẵn<textarea value={selected.prefilledMessage||''} onChange={event=>patchChannel(selected.id,{prefilledMessage:event.target.value})} placeholder="Xin chào, tôi cần tư vấn về {page_title}: {page_url}" className="min-h-24 border border-slate-200 rounded-xl p-3 font-normal"/></label></div><div className="grid sm:grid-cols-2 gap-3 text-xs"><label className="p-3 border rounded-xl flex gap-2"><input type="checkbox" checked={selected.enabled} onChange={event=>patchChannel(selected.id,{enabled:event.target.checked})}/> Bật kênh này</label><label className="p-3 border rounded-xl flex gap-2"><input type="checkbox" checked={selected.newTab} onChange={event=>patchChannel(selected.id,{newTab:event.target.checked})}/> Mở tab mới</label><label className="p-3 border rounded-xl flex gap-2"><input type="checkbox" checked={selected.desktopEnabled} onChange={event=>patchChannel(selected.id,{desktopEnabled:event.target.checked})}/> Hiện trên desktop</label><label className="p-3 border rounded-xl flex gap-2"><input type="checkbox" checked={selected.mobileEnabled} onChange={event=>patchChannel(selected.id,{mobileEnabled:event.target.checked})}/> Hiện trên mobile</label></div></div>:<div className="min-h-[400px] grid place-items-center text-center text-slate-400"><div><MonitorSmartphone className="mx-auto mb-3"/><p>Thêm hoặc chọn một kênh để cấu hình.</p></div></div>}
        <section className="mt-8 pt-6 border-t space-y-4"><h2 className="font-bold text-slate-900">Giao diện widget</h2><div className="grid sm:grid-cols-2 gap-4"><label className="grid gap-2 text-xs font-bold">Chế độ<select value={config.mode} onChange={event=>patch({mode:event.target.value as ContactWidgetConfig['mode']})} className="h-11 border rounded-xl px-3 font-normal"><option value="hub">Contact Hub thu gọn</option><option value="stack">Danh sách nút dọc</option></select></label><label className="grid gap-2 text-xs font-bold">Vị trí<select value={config.position} onChange={event=>patch({position:event.target.value as ContactWidgetConfig['position']})} className="h-11 border rounded-xl px-3 font-normal"><option value="right">Góc phải</option><option value="left">Góc trái</option></select></label><label className="grid gap-2 text-xs font-bold">Tiêu đề panel<input value={config.panelTitle} onChange={event=>patch({panelTitle:event.target.value})} className="h-11 border rounded-xl px-3 font-normal"/></label><label className="grid gap-2 text-xs font-bold">Mô tả panel<input value={config.panelSubtitle} onChange={event=>patch({panelSubtitle:event.target.value})} className="h-11 border rounded-xl px-3 font-normal"/></label></div><label className="flex gap-2 items-center text-xs font-bold"><input type="checkbox" checked={config.showMobileBar} onChange={event=>patch({showMobileBar:event.target.checked})}/> Bật thanh liên hệ nhanh dưới mobile</label>{config.showMobileBar&&<div><p className="text-[10px] text-slate-500 mb-2">Chọn tối đa 3 kênh:</p><div className="flex flex-wrap gap-2">{config.channels.filter(channel=>channel.enabled).map(channel=><label key={channel.id} className="text-[10px] border rounded-full px-3 py-2"><input type="checkbox" className="mr-1" checked={config.mobileBarChannelIds.includes(channel.id)} disabled={!config.mobileBarChannelIds.includes(channel.id)&&config.mobileBarChannelIds.length>=3} onChange={event=>patch({mobileBarChannelIds:event.target.checked?[...config.mobileBarChannelIds,channel.id]:config.mobileBarChannelIds.filter(id=>id!==channel.id)})}/>{channel.label}</label>)}</div></div>}</section>
      </main>
      <aside className="xl:sticky xl:top-20 bg-slate-900 rounded-2xl p-4 shadow-xl"><div className="flex items-center justify-between text-white mb-4"><strong className="text-sm">Xem trước</strong><div className="flex bg-white/10 rounded-lg p-1"><button onClick={()=>setPreviewMobile(false)} className={`w-8 h-8 grid place-items-center rounded ${!previewMobile?'bg-white text-slate-900':''}`}><Laptop size={15}/></button><button onClick={()=>setPreviewMobile(true)} className={`w-8 h-8 grid place-items-center rounded ${previewMobile?'bg-white text-slate-900':''}`}><Smartphone size={15}/></button></div></div><div className={`mx-auto relative overflow-hidden bg-gradient-to-b from-slate-50 to-blue-50 border-4 border-slate-700 ${previewMobile?'w-[250px] h-[470px] rounded-[28px]':'w-full h-[300px] rounded-xl'}`}><div className="h-10 bg-white border-b px-3 flex items-center text-[8px] font-bold text-blue-600">EZITRANS</div><div className="p-4"><div className="h-5 w-2/3 rounded bg-slate-200 mb-3"/><div className="h-2 w-full rounded bg-slate-100 mb-2"/><div className="h-2 w-4/5 rounded bg-slate-100"/></div><div className={`absolute bottom-4 ${config.position==='right'?'right-3':'left-3'}`}><div className="w-11 h-11 rounded-full text-white grid place-items-center shadow-xl" style={{background:config.primaryColor}}><MessageCircle size={18}/></div></div><div className={`absolute bottom-16 bg-white shadow-2xl rounded-xl p-2 w-44 ${config.position==='right'?'right-3':'left-3'}`}><strong className="text-[9px] block px-2 py-1">{config.panelTitle}</strong>{config.channels.filter(channel=>channel.enabled&&channel.value).slice(0,4).map(channel=><div key={channel.id} className="flex items-center gap-2 p-1.5"><span className="w-7 h-7 rounded-lg" style={{background:channel.color}}/><span className="text-[8px] font-bold">{channel.label}</span></div>)}</div></div><p className="text-[10px] text-slate-400 text-center mt-3">Preview minh họa trạng thái đang mở</p></aside>
    </div>
  </div>;
}
