export const CORE_HOOKS = {
  SEO_META: 'seo.meta',
  ADMIN_SIDEBAR_ITEMS: 'admin.sidebar.items',
  ADMIN_DASHBOARD_CARDS: 'admin.dashboard.cards',
  SETTINGS_PANELS: 'settings.panels',
  MEDIA_VALIDATE_FILE: 'media.validateFile',
  MEDIA_BEFORE_UPLOAD: 'media.beforeUpload',
  MEDIA_AFTER_UPLOAD: 'media.afterUpload',
  MEDIA_TRANSFORM_URL: 'media.transformUrl',
  MEDIA_LIBRARY_ACTIONS: 'media.library.actions',
  CONTENT_VALIDATE: 'content.validate',
  CONTENT_BEFORE_SAVE: 'content.beforeSave',
  CONTENT_AFTER_SAVE: 'content.afterSave',
  CONTENT_BEFORE_PUBLISH: 'content.beforePublish',
  CONTENT_AFTER_PUBLISH: 'content.afterPublish',
  CONTENT_TRANSFORM_SLUG: 'content.transformSlug',
  CONTENT_TRANSFORM_EXCERPT: 'content.transformExcerpt',
  CONTENT_FETCHED: 'content.fetched',
} as const;
