"use client";
import Link from 'next/link';
import { Bell, CheckCheck, Inbox, Loader2 } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
export interface AdminNotificationItem { id: number; type: string; title: string; message: string; href?: string | null; isRead: boolean; createdAt: string; }
interface Props { notifications: AdminNotificationItem[]; unreadCount: number; loading: boolean; onRefresh: () => void; onRead: (id: number) => Promise<void>; onReadAll: () => Promise<void>; }
function relativeTime(value: string) { const seconds = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 1000)); if (seconds < 60) return 'Vừa xong'; if (seconds < 3600) return `${Math.floor(seconds / 60)} phút trước`; if (seconds < 86400) return `${Math.floor(seconds / 3600)} giờ trước`; if (seconds < 604800) return `${Math.floor(seconds / 86400)} ngày trước`; return new Date(value).toLocaleDateString('vi-VN'); }
export default function NotificationCenter({ notifications, unreadCount, loading, onRefresh, onRead, onReadAll }: Props) {
  const [open, setOpen] = useState(false); const containerRef = useRef<HTMLDivElement>(null);
  useEffect(() => { const close = (event: MouseEvent) => { if (!containerRef.current?.contains(event.target as Node)) setOpen(false); }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close); }, []);
  return <div ref={containerRef} className="relative">
    <button id="admin-notification-toggle" type="button" aria-label={`Thông báo${unreadCount ? `, ${unreadCount} chưa đọc` : ''}`} aria-expanded={open} onClick={() => { setOpen(v => !v); if (!open) onRefresh(); }} className="relative p-1.5 text-slate-400 hover:text-brand-600 dark:hover:text-brand-400 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg transition-all"><Bell size={16} />{unreadCount > 0 && <span className="absolute -right-1.5 -top-1.5 min-w-4 h-4 px-1 rounded-full bg-gradient-to-r from-rose-500 to-orange-400 text-white text-[9px] font-black flex items-center justify-center ring-2 ring-white dark:ring-slate-900">{unreadCount > 99 ? '99+' : unreadCount}</span>}</button>
    {open && <div className="absolute right-0 top-10 z-50 w-[min(380px,calc(100vw-24px))] overflow-hidden rounded-2xl border border-slate-200/80 dark:border-slate-700 bg-white/95 dark:bg-slate-900/95 backdrop-blur-xl shadow-2xl shadow-slate-900/20">
      <div className="flex items-center justify-between px-4 py-3.5 border-b border-slate-100 dark:border-slate-800 bg-gradient-to-r from-brand-50/80 to-indigo-50/50 dark:from-brand-500/10 dark:to-indigo-500/5"><div><h2 className="text-sm font-extrabold text-slate-800 dark:text-white">Thông báo</h2><p className="text-[10px] text-slate-500 mt-0.5">{unreadCount ? `${unreadCount} thông báo chưa đọc` : 'Bạn đã xem tất cả thông báo'}</p></div>{unreadCount > 0 && <button id="admin-notifications-read-all" onClick={onReadAll} className="flex items-center gap-1 text-[10px] font-bold text-brand-600 dark:text-brand-400 hover:underline"><CheckCheck size={13} /> Đọc tất cả</button>}</div>
      <div className="max-h-[420px] overflow-y-auto">{loading ? <div className="flex items-center justify-center gap-2 py-12 text-xs text-slate-400"><Loader2 size={16} className="animate-spin" /> Đang tải...</div> : notifications.length === 0 ? <div className="py-12 text-center"><Inbox size={30} className="mx-auto text-slate-300 mb-3" /><p className="text-xs font-semibold text-slate-500">Chưa có thông báo nào</p></div> : notifications.map(item => <Link key={item.id} href={item.href || '#'} onClick={() => { if (!item.isRead) void onRead(item.id); setOpen(false); }} className={`relative flex gap-3 px-4 py-3.5 border-b border-slate-100/80 dark:border-slate-800/80 transition-colors hover:bg-brand-50/60 dark:hover:bg-slate-800 ${item.isRead ? '' : 'bg-indigo-50/50 dark:bg-indigo-500/5'}`}><span className={`mt-1 flex h-8 w-8 shrink-0 items-center justify-center rounded-xl ${item.isRead ? 'bg-slate-100 text-slate-400 dark:bg-slate-800' : 'bg-gradient-to-br from-brand-500 to-indigo-500 text-white shadow-md shadow-brand-500/20'}`}><Inbox size={15} /></span><span className="min-w-0 flex-1"><span className={`block text-xs ${item.isRead ? 'font-semibold text-slate-700 dark:text-slate-300' : 'font-extrabold text-slate-900 dark:text-white'}`}>{item.title}</span><span className="block mt-1 text-[11px] leading-relaxed text-slate-500 line-clamp-2">{item.message}</span><span className="block mt-1.5 text-[9px] font-semibold text-slate-400">{relativeTime(item.createdAt)}</span></span>{!item.isRead && <span className="absolute right-3 top-4 h-2 w-2 rounded-full bg-brand-500 ring-4 ring-brand-100 dark:ring-brand-500/20" />}</Link>)}</div>
      <Link href="/admin/submissions" onClick={() => setOpen(false)} className="block px-4 py-3 text-center text-[11px] font-bold text-brand-600 dark:text-brand-400 hover:bg-slate-50 dark:hover:bg-slate-800">Mở Hộp thư Form</Link>
    </div>}
  </div>;
}
