import Link from 'next/link';
import { Calendar, User, ArrowRight, ChevronLeft, ChevronRight } from 'lucide-react';
import Header from './Header';
import Footer from './Footer';
import Breadcrumbs from '@/components/Breadcrumbs';
import { generatePostUrl, formatDateWordPress } from '@/lib/permalink';

export default function AuthorPage({ author, posts = [], settings = {}, pagination, skipHeader = false, skipFooter = false }: any) {
  const name = author.name || author.username;
  const initials = name.split(/\s+/).map((part: string) => part[0]).join('').slice(0, 2).toUpperCase();
  const structure = settings.permalink_structure || '/%postname%.html';
  const pageUrl = (page: number) => `/author/${author.username}?page=${page}`;
  return <div className="ezi-theme">{!skipHeader && <Header settings={settings}/>}<section className="ezi-post-hero ezi-page-hero"><div className="ezi-container"><div className="ezi-post-hero-breadcrumbs"><Breadcrumbs settings={settings} items={[{label: settings.seo_breadcrumbs_home || 'Trang chủ', url: '/'},{label: `Tác giả: ${name}`}]} /></div><div className="ezi-author-head"><div className="ezi-author-avatar">{initials}</div><div><span className="ezi-eyebrow">Đội ngũ biên tập Ezitrans</span><h1>{name}</h1><p>{pagination.totalItems} bài viết đã xuất bản</p></div></div></div></section><main className="ezi-static-page-main"><div className="ezi-container">{posts.length === 0 ? <div className="ezi-empty-state"><User size={44}/><h2>Tác giả chưa có bài viết công khai</h2></div> : <div className="ezi-archive-grid">{posts.map((post: any) => { const href=generatePostUrl(post, structure); return <article key={post.id} className="ezi-archive-card"><Link href={href} className="ezi-archive-card-image-wrapper">{post.featuredImage?.url?<img src={post.featuredImage.url} alt={post.title} className="ezi-archive-card-image"/>:<div className="ezi-archive-card-placeholder"><User size={30}/><span>Ezitrans</span></div>}</Link><div className="ezi-archive-card-body"><div className="ezi-archive-card-meta"><span><Calendar size={13}/>{formatDateWordPress(post.createdAt, settings.date_format || 'd/m/Y', settings.site_language || 'vi')}</span></div><h2 className="ezi-archive-card-title"><Link href={href}>{post.title}</Link></h2><p className="ezi-archive-card-excerpt">{post.excerpt || 'Đọc bài viết mới từ đội ngũ Ezitrans.'}</p><Link href={href} className="ezi-archive-card-readmore">Đọc tiếp <ArrowRight size={14}/></Link></div></article>})}</div>}{pagination.totalPages>1&&<nav className="ezi-pagination-container" aria-label="Phân trang tác giả"><div className="ezi-pagination-list">{pagination.currentPage>1&&<Link href={pageUrl(pagination.currentPage-1)} className="ezi-pagination-item"><ChevronLeft size={16}/></Link>}{Array.from({length:pagination.totalPages},(_:any,i:number)=>i+1).filter((p:number)=>Math.abs(p-pagination.currentPage)<=2||p===1||p===pagination.totalPages).map((p:number)=><Link key={p} href={pageUrl(p)} className={`ezi-pagination-item ${p===pagination.currentPage?'active':''}`}>{p}</Link>)}{pagination.currentPage<pagination.totalPages&&<Link href={pageUrl(pagination.currentPage+1)} className="ezi-pagination-item"><ChevronRight size={16}/></Link>}</div></nav>}</div></main>{!skipFooter&&<Footer settings={settings}/>}</div>;
}
