import Link from 'next/link';
import { ArrowRight, Calendar, ChevronLeft, ChevronRight, ImageIcon, User } from 'lucide-react';
import { formatDateWordPress, generatePostUrl } from '@/lib/permalink';

export interface StarterPagination {currentPage:number;totalPages:number;totalItems:number;startItem:number;endItem:number}
export function StarterArchiveHero({eyebrow,title,description,summary}:{eyebrow:string;title:string;description?:string;summary?:string}){return <section className="starter-archive-hero"><div className="starter-container"><span className="starter-eyebrow">{eyebrow}</span><h1>{title}</h1>{description&&<p>{description}</p>}{summary&&<div className="starter-archive-summary">{summary}</div>}</div></section>}
export function StarterPostGrid({posts,settings,emptyText='Chưa có nội dung được xuất bản.'}:{posts:any[];settings:Record<string,string>;emptyText?:string}){if(!posts.length)return <div className="starter-empty">{emptyText}</div>;return <div className="starter-post-grid">{posts.map(post=>{const href=generatePostUrl(post,settings.permalink_structure||'/%postname%.html');const date=formatDateWordPress(post.publishedAt||post.createdAt,settings.date_format||'d/m/Y',settings.site_language||'vi');return <article className="starter-post" key={post.id}><Link href={href} className="starter-post-media">{post.featuredImage?.url?<img src={post.featuredImage.url} alt={post.title}/>:<span className="starter-card-placeholder"><ImageIcon size={30}/></span>}</Link><div className="starter-post-body"><div className="starter-post-meta"><span><Calendar size={12}/>{date}</span>{post.author?.name&&<span><User size={12}/>{post.author.name}</span>}</div><h2><Link href={href}>{post.title}</Link></h2>{post.excerpt&&<p>{post.excerpt}</p>}<Link href={href} className="starter-readmore">Đọc tiếp <ArrowRight size={14}/></Link></div></article>})}</div>}
export function StarterPaginationNav({pagination,basePath,query={}}:{pagination?:StarterPagination;basePath:string;query?:Record<string,string>}){if(!pagination||pagination.totalPages<=1)return null;const pageHref=(page:number)=>{const params=new URLSearchParams(query);if(page>1)params.set('page',String(page));else params.delete('page');const suffix=params.toString();return `${basePath}${suffix?`?${suffix}`:''}`};const pages=Array.from({length:pagination.totalPages},(_,i)=>i+1).filter(page=>page===1||page===pagination.totalPages||Math.abs(page-pagination.currentPage)<=2);return <nav className="starter-pagination" aria-label="Phân trang">{pagination.currentPage>1&&<Link href={pageHref(pagination.currentPage-1)} aria-label="Trang trước"><ChevronLeft size={17}/></Link>}{pages.map((page,index)=><span key={page}>{index>0&&page-pages[index-1]>1&&<i>…</i>}<Link href={pageHref(page)} className={page===pagination.currentPage?'active':''}>{page}</Link></span>)}{pagination.currentPage<pagination.totalPages&&<Link href={pageHref(pagination.currentPage+1)} aria-label="Trang sau"><ChevronRight size={17}/></Link>}</nav>}
export function StarterArchiveLayout({children}:{children:React.ReactNode}){return <main className="starter-section starter-section-alt"><div className="starter-container">{children}</div></main>}
