import http from 'node:http';import crypto from 'node:crypto';import fs from 'node:fs';import fsp from 'node:fs/promises';import path from 'node:path';import {spawn} from 'node:child_process';
const port=Number(process.env.UPDATE_AGENT_PORT||4577);const token=process.env.UPDATE_AGENT_TOKEN||'';const simulate=process.env.SIMULATE_UPDATES!=='false';const workspace=process.env.COMPOSE_PROJECT_DIR||'/workspace';const service=process.env.APP_SERVICE_NAME||'app';const repository=process.env.CORE_IMAGE_REPOSITORY||'lexi-cms/core';const readyUrl=process.env.APP_READY_URL||'http://app:3000/api/health/ready';const healthToken=process.env.INTERNAL_HEALTH_TOKEN||'';const lockFile=process.env.UPDATE_LOCK_FILE||'/agent/content/.update.lock';const logDir=process.env.UPDATE_LOG_DIR||'/agent/content/logs';
function json(res,status,payload){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(payload));}
function authorized(req){if(!token)return false;const supplied=(req.headers.authorization||'').replace(/^Bearer /,'');const a=Buffer.from(token);const b=Buffer.from(supplied);return a.length===b.length&&crypto.timingSafeEqual(a,b);}
function command(cmd,args,timeout=600000,env={}){return new Promise((resolve)=>{const child=spawn(cmd,args,{cwd:workspace,env:{...process.env,...env},shell:process.platform==='win32'});let stdout='',stderr='';const timer=setTimeout(()=>child.kill('SIGKILL'),timeout);child.stdout.on('data',d=>stdout+=d);child.stderr.on('data',d=>stderr+=d);child.on('error',e=>{clearTimeout(timer);resolve({success:false,code:-1,stdout,stderr,error:e.message});});child.on('close',code=>{clearTimeout(timer);resolve({success:code===0,code,stdout:stdout.trim(),stderr:stderr.trim()});});});}
async function readBody(req){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>100000)throw new Error('Payload too large.');}return raw?JSON.parse(raw):{};}
function allowedImage(image){return typeof image==='string'&&image.startsWith(`${repository}@sha256:`)&&/^.+@sha256:[a-f0-9]{64}$/.test(image);}
async function acquire(jobId){await fsp.mkdir(path.dirname(lockFile),{recursive:true});try{return await fsp.open(lockFile,'wx').then(async h=>{await h.writeFile(JSON.stringify({jobId,createdAt:new Date().toISOString()}));await h.close();return true;});}catch{return false;}}
async function release(){await fsp.rm(lockFile,{force:true});}
async function log(jobId,event,data={}){await fsp.mkdir(logDir,{recursive:true});await fsp.appendFile(path.join(logDir,`${jobId}.jsonl`),JSON.stringify({time:new Date().toISOString(),event,...data})+'\n');}
async function ready(){const response=await fetch(readyUrl,{headers:healthToken?{Authorization:`Bearer ${healthToken}`}:{},signal:AbortSignal.timeout(10000)});return {success:response.ok,status:response.status,payload:await response.json().catch(()=>null)};}
async function preflight(image){const checks={imageAllowed:allowedImage(image),docker:await command('docker',['version','--format','{{.Server.Version}}'],15000),compose:await command('docker',['compose','version'],15000),disk:await command('docker',['system','df'],30000)};return {success:checks.imageAllowed&&checks.docker.success&&checks.compose.success,checks};}
async function update(body){const {jobId,targetImage,currentVersion,targetVersion}=body;if(!jobId||!allowedImage(targetImage))return {success:false,error:'Invalid job ID or target image. Image digest/repository is not allowed.'};if(!(await acquire(jobId)))return {success:false,error:'Another update is already running.',locked:true};try{await log(jobId,'started',{targetImage,currentVersion,targetVersion,simulate});const checks=await preflight(targetImage);await log(jobId,'preflight',{checks});if(!checks.success)return {success:false,error:'Preflight failed.',checks};if(simulate){await log(jobId,'completed',{simulated:true});return {success:true,simulated:true,message:'Simulation completed. No Docker changes were made.',checks};}
 const inspect=await command('docker',['compose','images','-q',service],30000);const previousImageId=inspect.stdout.split(/\s+/)[0]||'';const rollbackTag=`${repository}:rollback-${jobId}`;if(previousImageId){const tagged=await command('docker',['tag',previousImageId,rollbackTag],30000);if(!tagged.success)return {success:false,error:'Could not create rollback image tag.',tagged};}
 const pull=await command('docker',['pull',targetImage],900000);await log(jobId,'pull',{pull});if(!pull.success)return {success:false,error:'Image pull failed.',pull};
 const migrate=await command('docker',['run','--rm','--network',process.env.COMPOSE_PROJECT_NAME?`${process.env.COMPOSE_PROJECT_NAME}_default`:'bridge','-e',`DATABASE_URL=${process.env.DATABASE_URL||''}`,targetImage,'npx','prisma','migrate','deploy'],600000);await log(jobId,'migrate',{migrate});if(!migrate.success)return {success:false,error:'Database migration failed.',migrate,rollbackTag};
 const env={CORE_IMAGE_REPOSITORY:targetImage.split('@')[0],CORE_VERSION:targetImage};const restart=await command('docker',['compose','up','-d','--no-build','--force-recreate',service],600000,env);await log(jobId,'restart',{restart});if(!restart.success)return {success:false,error:'App restart failed.',restart,rollbackTag};
 let health=null;for(let i=0;i<12;i++){await new Promise(r=>setTimeout(r,5000));try{health=await ready();if(health.success)break;}catch(e){health={success:false,error:e.message};}}await log(jobId,'health',{health});if(!health?.success){return {success:false,error:'Readiness check failed after update.',health,rollback:{required:true,rollbackTag}};}await log(jobId,'completed',{simulated:false});return {success:true,simulated:false,message:'Core update completed and readiness check passed.',rollbackTag,health};}finally{await release();}}
async function rollback(body){const tag=body.rollbackTag;if(typeof tag!=='string'||!tag.startsWith(`${repository}:rollback-`))return {success:false,error:'Rollback tag is not allowed.'};if(!(await acquire(body.jobId||'rollback')))return {success:false,error:'Another update is running.'};try{if(simulate)return {success:true,simulated:true,message:'Rollback simulation completed.'};const env={CORE_IMAGE_REPOSITORY:tag.split(':')[0],CORE_VERSION:tag};const restart=await command('docker',['compose','up','-d','--no-build','--force-recreate',service],600000,env);return {success:restart.success,simulated:false,restart,message:restart.success?'Rollback container started.':'Rollback failed.'};}finally{await release();}}
const server=http.createServer(async(req,res)=>{try{if(req.url==='/health'&&req.method==='GET')return json(res,200,{success:true,status:'alive',simulate});if(!authorized(req))return json(res,401,{success:false,error:'Unauthorized'});if(req.url==='/diagnostics'&&req.method==='GET'){const current=await command('docker',['compose','images',service],30000);return json(res,200,{success:true,simulateUpdates:simulate,composeProjectDir:workspace,currentImage:current.stdout,dockerVersion:await command('docker',['version'],30000),composeVersion:await command('docker',['compose','version'],30000),dockerSystemDf:await command('docker',['system','df'],30000),locked:fs.existsSync(lockFile)});}const body=await readBody(req);if(req.url==='/core/preflight'&&req.method==='POST')return json(res,200,await preflight(body.targetImage));if(req.url==='/core/update'&&req.method==='POST'){const result=await update(body);return json(res,result.success?200:409,result);}if(req.url==='/core/rollback'&&req.method==='POST'){const result=await rollback(body);return json(res,result.success?200:409,result);}return json(res,404,{success:false,error:'Not found'});}catch(e){return json(res,500,{success:false,error:e.message||'Agent error'});}});server.listen(port,'0.0.0.0',()=>console.log(`Lexi Update Agent listening on ${port}; simulation=${simulate}`));
