import { AIDslNode } from './aiProvider';

// Helper to generate a unique random ID for CraftJS nodes
function generateNodeId(): string {
  return Math.random().toString(36).substring(2, 12).toUpperCase();
}

// Security Validation: Scan for malicious elements and reject if found
export function validateSafety(dsl: AIDslNode): void {
  const dslStr = JSON.stringify(dsl).toLowerCase();

  // 1. Reject script tags
  if (dslStr.includes('<script') || dslStr.includes('</script>')) {
    throw new Error('Phát hiện thẻ <script> độc hại. Apply bị từ chối vì lý do bảo mật.');
  }

  // 2. Reject inline event handlers (e.g. onerror, onload, onclick)
  if (/\bon[a-z]+\s*=/i.test(dslStr)) {
    throw new Error('Phát hiện sự kiện Javascript nội tuyến (inline event handler). Apply bị từ chối vì lý do bảo mật.');
  }

  // 3. Reject javascript: protocol references
  if (/javascript\s*:/i.test(dslStr)) {
    throw new Error('Phát hiện giao thức "javascript:" độc hại. Apply bị từ chối vì lý do bảo mật.');
  }

  // 4. Scan nested elements to reject dangerous iframe tags
  // We allow standard iframe embeds in HtmlBlock only if they point to reputable video/map servers (youtube.com, vimeo.com, google.com/maps)
  function checkNodeSafety(node: AIDslNode) {
    if (node.type !== 'accordion') {
      const textProperties = [node.text, node.link, node.url, node.videoUrl];
      for (const text of textProperties) {
        if (text && (text.includes('<iframe') || text.includes('</iframe>'))) {
          throw new Error('Phát hiện thẻ iframe nhúng trong văn bản thông thường. Vui lòng sử dụng khối HTML chuyên dụng.');
        }
      }
    }
    
    // For Accordions
    if (node.items) {
      for (const item of node.items) {
        if (item.title?.includes('<script') || item.content?.includes('<script') || 
            /\bon[a-z]+\s*=/i.test(item.title) || /\bon[a-z]+\s*=/i.test(item.content)) {
          throw new Error('Phát hiện mã script hoặc sự kiện Javascript trong Accordion.');
        }
      }
    }

    if (node.children) {
      node.children.forEach(checkNodeSafety);
    }
  }

  checkNodeSafety(dsl);
}

// Property Sanitizer: Trims strings and strips inline script links
function sanitizeString(val: string): string {
  let clean = val.replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, '');
  clean = clean.replace(/\bon[a-z]+\s*=\s*(['"][^'"]*['"]|[^\s>]+)/gi, '');
  clean = clean.replace(/javascript\s*:\s*[^\s"'>]*/gi, '');
  return clean.trim();
}

function sanitizeNodeProps(node: AIDslNode): void {
  if (node.text) node.text = sanitizeString(node.text);
  if (node.link) node.link = sanitizeString(node.link);
  if (node.url) node.url = sanitizeString(node.url);
  if (node.videoUrl) node.videoUrl = sanitizeString(node.videoUrl);

  if (node.items) {
    node.items = node.items.map(item => ({
      title: sanitizeString(item.title),
      content: sanitizeString(item.content)
    }));
  }

  if (node.children) {
    node.children.forEach(sanitizeNodeProps);
  }
}

// Flat representation structure generated by the Transformer
export interface CraftNodeTree {
  rootNodeId: string;
  nodes: Record<string, {
    type: { resolvedName: string };
    isCanvas: boolean;
    props: Record<string, any>;
    displayName: string;
    parent: string | null;
    nodes: string[];
    linkedNodes: Record<string, string>;
  }>;
}

/**
 * Transforms a nested AIDslNode structure into a flat CraftJS CraftNodeTree representation.
 * @param dsl The root DSL node.
 * @param parentId The parent ID to attach the root to (default is null for isolated trees, 'ROOT' if replacing/appending on root).
 * @returns A CraftNodeTree containing the flat node mappings.
 */
export function transformDslToCraftNodeTree(dsl: AIDslNode, parentId: string | null = null): CraftNodeTree {
  // First, enforce safety rules and sanitize inputs
  validateSafety(dsl);
  sanitizeNodeProps(dsl);

  const flatNodes: Record<string, any> = {};
  
  // Choose ID for root node of this tree
  const rootNodeId = parentId === 'ROOT' ? 'ROOT' : generateNodeId();

  function compileNode(node: AIDslNode, id: string, parent: string | null): string {
    const { type, children, ...restProps } = node;
    
    let resolvedName = 'Container';
    let isCanvas = false;
    let displayName = 'Vùng chứa';
    let defaultProps: Record<string, any> = {};

    switch (type) {
      case 'section':
        resolvedName = 'Container';
        isCanvas = true;
        displayName = 'Vùng chứa';
        defaultProps = {
          paddingTop: '60px',
          paddingBottom: '60px',
          paddingLeft: '20px',
          paddingRight: '20px',
          flexDirection: 'column',
          backgroundColor: 'transparent',
          width: '100%',
        };
        break;
      case 'row':
        resolvedName = 'Container';
        isCanvas = true;
        displayName = 'Hàng (Grid)';
        defaultProps = {
          flexDirection: 'row',
          paddingTop: '0px',
          paddingBottom: '0px',
          paddingLeft: '0px',
          paddingRight: '0px',
          gap: '16px',
          width: '100%',
          backgroundColor: 'transparent',
        };
        break;
      case 'column':
        resolvedName = 'Container';
        isCanvas = true;
        displayName = 'Cột';
        defaultProps = {
          flexDirection: 'column',
          paddingTop: '0px',
          paddingBottom: '0px',
          paddingLeft: '0px',
          paddingRight: '0px',
          width: restProps.width || '100%',
          backgroundColor: 'transparent',
        };
        break;
      case 'heading':
        resolvedName = 'HeadingBlock';
        displayName = 'Tiêu đề';
        defaultProps = {
          text: 'Tiêu đề mới',
          level: 'h2',
          textColor: 'var(--site-color-text)',
          textAlign: 'left',
          marginBottom: '8px',
        };
        break;
      case 'text':
        resolvedName = 'TextBlock';
        displayName = 'Văn bản';
        defaultProps = {
          text: 'Văn bản mới',
          textColor: 'var(--site-color-text)',
          textAlign: 'left',
          marginBottom: '16px',
        };
        break;
      case 'image':
        resolvedName = 'ImageBlock';
        displayName = 'Hình ảnh';
        defaultProps = {
          url: '',
          alt: 'AI Design Image',
          widthMode: 'full',
        };
        break;
      case 'button':
        resolvedName = 'ButtonBlock';
        displayName = 'Nút bấm';
        defaultProps = {
          text: 'Nút bấm',
          backgroundColor: 'var(--site-color-primary)',
          textColor: '#ffffff',
          borderRadius: '8px',
          paddingTop: '12px',
          paddingBottom: '12px',
          paddingLeft: '24px',
          paddingRight: '24px',
          widthMode: 'inline',
        };
        break;
      case 'divider':
        resolvedName = 'DividerBlock';
        displayName = 'Đường kẻ';
        defaultProps = {
          thickness: '2px',
          color: '#cbd5e1',
          marginTop: '10px',
          marginBottom: '10px',
        };
        break;
      case 'video':
        resolvedName = 'VideoBlock';
        displayName = 'Video';
        defaultProps = {
          url: '',
        };
        break;
      case 'spacer':
        resolvedName = 'SpacerBlock';
        displayName = 'Khoảng trống';
        defaultProps = {
          height: '30px',
        };
        break;
      case 'icon':
        resolvedName = 'IconBlock';
        displayName = 'Biểu tượng';
        defaultProps = {
          iconName: 'Smile',
          size: 24,
          color: 'var(--site-color-primary)',
        };
        break;
      case 'social_icons':
        resolvedName = 'SocialIconsBlock';
        displayName = 'Icon Mạng Xã Hội';
        defaultProps = {
          items: [
            { platform: 'facebook', link: 'https://facebook.com', colorMode: 'official' },
            { platform: 'twitter', link: 'https://twitter.com', colorMode: 'official' },
            { platform: 'youtube', link: 'https://youtube.com', colorMode: 'official' },
          ],
          shape: 'rounded',
          iconView: 'default',
          align: 'center',
        };
        break;
      case 'accordion':
        resolvedName = 'AccordionBlock';
        displayName = 'Sập mở (FAQ)';
        defaultProps = {
          items: [],
        };
        break;
      case 'carousel':
        resolvedName = 'CarouselBlock';
        displayName = 'Băng chuyền hình ảnh';
        defaultProps = {
          carouselName: 'Băng chuyền hình ảnh',
          images: [],
          imageResolution: 'large',
          navigation: 'arrows_dots',
        };
        break;
      case 'counter':
        resolvedName = 'CounterBlock';
        displayName = 'Bộ đếm';
        defaultProps = {
          startNumber: 0,
          endNumber: 100,
          prefix: '',
          suffix: '',
          duration: 2000,
          useThousandSeparator: true,
          title: 'Cool Number',
          titleTag: 'div',
        };
        break;
      case 'progress':
        resolvedName = 'ProgressBarBlock';
        displayName = 'Thanh tiến trình';
        defaultProps = {
          title: 'My Skill',
          percentage: 50,
          displayPercentage: true,
          barType: 'default',
          duration: 1500,
        };
        break;
    }

    // Special mapping for videoUrl -> url
    if (type === 'video' && restProps.videoUrl !== undefined) {
      restProps.url = restProps.videoUrl;
      delete restProps.videoUrl;
    }

    // Merge default props and supplied props
    const props = { ...defaultProps, ...restProps };

    const childIds: string[] = [];
    if (children && children.length > 0) {
      children.forEach(child => {
        const childId = generateNodeId();
        compileNode(child, childId, id);
        childIds.push(childId);
      });
    }

    flatNodes[id] = {
      type: { resolvedName },
      isCanvas,
      props,
      displayName,
      parent,
      nodes: childIds,
      linkedNodes: {},
    };

    return id;
  }

  compileNode(dsl, rootNodeId, parentId);

  return {
    rootNodeId,
    nodes: flatNodes
  };
}

/**
 * Translates a flat CraftJS node tree mapping back into a nested AIDslNode structure.
 * @param nodes The flat key-value map of nodes from CraftJS query.serialize().
 * @param rootId The root ID of the sub-tree to convert.
 * @returns The nested AIDslNode representation.
 */
export function transformCraftNodeTreeToDsl(nodes: Record<string, any>, rootId: string): AIDslNode {
  const node = nodes[rootId];
  if (!node) {
    throw new Error(`Node ${rootId} not found in the provided builder tree`);
  }

  const resolvedName = node.type?.resolvedName || node.name || '';
  let type: AIDslNode['type'] = 'section';

  if (resolvedName === 'Container') {
    if (rootId === 'ROOT' || node.props?.paddingTop === '60px' || node.props?.paddingBottom === '60px' || node.parent === 'ROOT') {
      type = 'section';
    } else if (node.props?.flexDirection === 'row') {
      type = 'row';
    } else {
      const parentId = node.parent;
      const parent = parentId ? nodes[parentId] : null;
      if (parent && (parent.type?.resolvedName === 'Container' || parent.name === 'Container') && parent.props?.flexDirection === 'row') {
        type = 'column';
      } else {
        type = 'section';
      }
    }
  } else if (resolvedName === 'HeadingBlock') {
    type = 'heading';
  } else if (resolvedName === 'TextBlock') {
    type = 'text';
  } else if (resolvedName === 'ImageBlock') {
    type = 'image';
  } else if (resolvedName === 'ButtonBlock') {
    type = 'button';
  } else if (resolvedName === 'DividerBlock') {
    type = 'divider';
  } else if (resolvedName === 'VideoBlock') {
    type = 'video';
  } else if (resolvedName === 'SpacerBlock') {
    type = 'spacer';
  } else if (resolvedName === 'IconBlock') {
    type = 'icon';
  } else if (resolvedName === 'SocialIconsBlock') {
    type = 'social_icons';
  } else if (resolvedName === 'AccordionBlock') {
    type = 'accordion';
  } else if (resolvedName === 'CarouselBlock') {
    type = 'carousel';
  }

  // Copy relevant properties from props (excluding children nodes)
  const dslProps = { ...node.props };
  
  if (resolvedName === 'VideoBlock') {
    if (dslProps.url !== undefined) {
      dslProps.videoUrl = dslProps.url;
      delete dslProps.url;
    }
  }

  // Clean up internally managed node tree properties
  delete dslProps.nodes;
  delete dslProps.children;

  const dsl: AIDslNode = {
    type,
    ...dslProps
  };

  // Recursively add children nodes
  if (node.nodes && Array.isArray(node.nodes) && node.nodes.length > 0) {
    dsl.children = node.nodes
      .filter((childId: string) => nodes[childId])
      .map((childId: string) => transformCraftNodeTreeToDsl(nodes, childId));
  }

  return dsl;
}
