import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { getCurrentUser } from '@/lib/session';
import { userCan } from '@/lib/capabilities';
import { scanAllThemes } from '@/lib/updates/runtimePackages';
import { fieldStorageKey, flattenCustomizer, normalizeCustomizerValue } from '@/lib/themes/customizer';
import { defaultThemeConfig, getConfigPath, getThemeConfig, setConfigPath } from '@/lib/themes/customizerRegistry';

async function context(themeId:string){const user=await getCurrentUser();if(!await userCan(user,'manage_themes'))return {error:NextResponse.json({success:false,error:'Bạn không có quyền quản lý giao diện'},{status:403})};const theme=scanAllThemes().validThemesData.find(item=>item.manifest.id===themeId);if(!theme)return {error:NextResponse.json({success:false,error:'Theme không tồn tại hoặc không hợp lệ'},{status:404})};return {theme:theme.manifest};}
export async function GET(_request:Request,{params}:{params:Promise<{themeId:string}>}){const {themeId}=await params;const found=await context(themeId);if(found.error)return found.error;const panels=found.theme?.customizer||[];const fields=flattenCustomizer(panels);const keys=[...new Set(fields.filter(x=>x.field.type!=='shortcut').map(x=>fieldStorageKey(themeId,x.field)))];const rows=await prisma.setting.findMany({where:{key:{in:keys}}});const stored=Object.fromEntries(rows.map(row=>[row.key,row.value]));const configs=new Map<string,unknown>();const values:Record<string,string>={};for(const {field} of fields){if(field.type==='shortcut')continue;const key=fieldStorageKey(themeId,field);if(field.configPath){if(!configs.has(key))configs.set(key,getThemeConfig(themeId,field.settingKey||field.id,stored[key]));const value=getConfigPath(configs.get(key),field.configPath);values[field.id]=field.type==='repeater'?JSON.stringify(Array.isArray(value)&&typeof value[0]!=='object'?value.map(text=>({text})):value??[]):String(value??field.default??'')}else values[field.id]=stored[key]??String(field.default??'')}return NextResponse.json({success:true,theme:{id:found.theme!.id,name:found.theme!.name},panels,values});}
export async function POST(request:Request,{params}:{params:Promise<{themeId:string}>}){const {themeId}=await params;const found=await context(themeId);if(found.error)return found.error;const body=await request.json();if(!body.values||typeof body.values!=='object')return NextResponse.json({success:false,error:'Dữ liệu không hợp lệ'},{status:400});const fields=flattenCustomizer(found.theme?.customizer||[]);const allowed=new Map(fields.filter(x=>x.field.type!=='shortcut').map(x=>[x.field.id,x.field]));for(const key of Object.keys(body.values))if(!allowed.has(key))return NextResponse.json({success:false,error:`Field không được phép: ${key}`},{status:400});const existingKeys=[...new Set([...allowed.values()].map(field=>fieldStorageKey(themeId,field)))];const rows=await prisma.setting.findMany({where:{key:{in:existingKeys}}});const stored=Object.fromEntries(rows.map(row=>[row.key,row.value]));const updates=new Map<string,string>();const configs=new Map<string,unknown>();for(const [id,input] of Object.entries(body.values)){const field=allowed.get(id)!;const key=fieldStorageKey(themeId,field);const normalized=normalizeCustomizerValue(field,input);if(field.configPath){if(!configs.has(key))configs.set(key,getThemeConfig(themeId,field.settingKey||field.id,stored[key])||defaultThemeConfig(themeId,field.settingKey||field.id));let parsed:unknown=normalized;if(field.type==='toggle')parsed=normalized==='true';else if(field.type==='number')parsed=Number(normalized);else if(field.type==='repeater'){const arr=JSON.parse(normalized);parsed=(field.itemFields?.length===1&&field.itemFields[0].id==='text')?arr.map((item:Record<string,unknown>)=>String(item.text??'')):arr}configs.set(key,setConfigPath(configs.get(key),field.configPath,parsed))}else updates.set(key,normalized)}for(const [key,config] of configs)updates.set(key,JSON.stringify(config));await prisma.$transaction([...updates].map(([key,value])=>prisma.setting.upsert({where:{key},update:{value},create:{key,value}})));return NextResponse.json({success:true,message:'Đã xuất bản cấu hình website'});}
