'use client';
import { useEffect,useMemo,useRef,useState } from 'react';
import { useParams,useRouter } from 'next/navigation';
import { ArrowLeft,ChevronRight,Loader2,Monitor,RefreshCw,Save,Smartphone,Tablet } from 'lucide-react';
import type { ThemeCustomizerPanel,ThemeCustomizerSection } from '@/lib/themes/manifest.schema';
import CustomizerField from '@/components/theme-customizer/CustomizerField';
import { broadcastSettings } from '@/hooks/useThemeCustomizer';
import '@/components/theme-customizer/customizer.css';
type Payload={theme:{id:string;name:string};panels:ThemeCustomizerPanel[];values:Record<string,string>};
export default function ThemeCustomizerPage(){const {themeId}=useParams<{themeId:string}>();const router=useRouter();const [data,setData]=useState<Payload|null>(null);const [values,setValues]=useState<Record<string,string>>({});const [saved,setSaved]=useState<Record<string,string>>({});const [panel,setPanel]=useState<ThemeCustomizerPanel|null>(null);const [section,setSection]=useState<ThemeCustomizerSection|null>(null);const [mode,setMode]=useState<'desktop'|'tablet'|'mobile'>('desktop');const [saving,setSaving]=useState(false);const [toast,setToast]=useState<{type:'success'|'error';text:string}|null>(null);const frame=useRef<HTMLIFrameElement>(null);const session=useMemo(()=>crypto.randomUUID(),[]);const dirty=JSON.stringify(values)!==JSON.stringify(saved);
 useEffect(()=>{fetch(`/api/themes/${themeId}/customizer`).then(r=>r.json()).then(payload=>{if(!payload.success)throw new Error(payload.error);setData(payload);setValues(payload.values);setSaved(payload.values)}).catch(e=>setToast({type:'error',text:e.message}))},[themeId]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty)e.preventDefault()};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty]);
 const update=(id:string,value:string)=>setValues(prev=>{const next={...prev,[id]:value};broadcastSettings(next,{themeId,sessionId:session});return next});
 const save=async()=>{setSaving(true);setToast(null);try{const response=await fetch(`/api/themes/${themeId}/customizer`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({values})});const payload=await response.json();if(!response.ok||!payload.success)throw new Error(payload.error||'Không thể lưu');setSaved(values);setToast({type:'success',text:payload.message})}catch(e){setToast({type:'error',text:e instanceof Error?e.message:'Không thể lưu'})}finally{setSaving(false)}};
 const chooseSection=(item:ThemeCustomizerSection)=>{setSection(item);if(item.previewPath&&frame.current)frame.current.src=`${item.previewPath}?customize_preview=1&theme=${themeId}&customizer_session=${session}`;setTimeout(()=>frame.current?.contentWindow?.postMessage({type:'CUSTOMIZER_SCROLL',anchor:item.previewAnchor},location.origin),500)};
 const back=()=>{if(section)setSection(null);else if(panel)setPanel(null);else router.push('/admin/settings/themes')};const width=mode==='desktop'?'100%':mode==='tablet'?'768px':'390px';const preview=`/?customize_preview=1&theme=${themeId}&customizer_session=${session}`;
 return <div className="customizer-shell"><aside className="customizer-sidebar"><header className="customizer-top"><button id="customizer-back" className="customizer-back" onClick={back}><ArrowLeft size={17}/></button><div className="customizer-title">{data?`Tùy biến ${data.theme.name}`:'Đang tải...'}</div><button id="customizer-publish" className="customizer-save" onClick={save} disabled={!dirty||saving}>{saving?<Loader2 size={15} className="animate-spin"/>:<Save size={15}/>} Lưu</button></header><div className="customizer-status">{dirty?'● Có thay đổi chưa lưu':'✓ Đã đồng bộ với website'}</div>{toast&&<div className={`customizer-toast ${toast.type}`}>{toast.text}</div>}<div className="customizer-scroll">{!data?<div style={{padding:30,textAlign:'center'}}><Loader2 className="animate-spin"/></div>:section?<><div className="customizer-breadcrumb"><button onClick={()=>setSection(null)}>‹ {panel?.title}</button><span>/</span><strong>{section.title}</strong></div><div className="customizer-fields">{section.fields.map(field=><CustomizerField key={field.id} field={field} value={values[field.id]??field.default??''} onChange={value=>update(field.id,value)}/>)}</div></>:panel?<><div className="customizer-breadcrumb"><button onClick={()=>setPanel(null)}>‹ Customize</button><strong>{panel.title}</strong></div>{panel.sections.map(item=><button className="customizer-section-button" key={item.id} onClick={()=>chooseSection(item)}><span>{item.title}</span><ChevronRight size={16}/></button>)}</>:data.panels.map(item=><button className="customizer-panel-button" key={item.id} onClick={()=>setPanel(item)}><span>{item.title}</span><ChevronRight size={16}/></button>)}</div></aside><main className="customizer-preview"><div className="customizer-toolbar"><button className={mode==='desktop'?'active':''} onClick={()=>setMode('desktop')} aria-label="Desktop"><Monitor size={17}/></button><button className={mode==='tablet'?'active':''} onClick={()=>setMode('tablet')} aria-label="Tablet"><Tablet size={17}/></button><button className={mode==='mobile'?'active':''} onClick={()=>setMode('mobile')} aria-label="Mobile"><Smartphone size={17}/></button><button onClick={()=>frame.current?.contentWindow?.location.reload()} aria-label="Tải lại"><RefreshCw size={16}/></button></div><div className="customizer-stage"><iframe id="customizer-preview-frame" ref={frame} title="Xem trước website" className="customizer-frame" src={preview} style={{width}} onLoad={()=>broadcastSettings(values,{themeId,sessionId:session})}/></div></main></div>}
